# 4 microservices and 2 databases (mongodb and mysql db)
# Note that the container names are important for the nginx routing rules nginx default.conf

version: "3.8"

services:
  # angular client
  client:
    build:
      context: ./client
    ports:
      - "4200:4200"
    container_name: client
    depends_on:
      - api
      - webapi

  # nodejs emart api
  api:
    build:
      context: ./nodeapi
    ports:
      - "5000:5000"
    restart: always
    container_name: api
    depends_on:
      - nginx
      - emongo

  # java books api
  webapi:
    build:
      context: ./javaapi
    ports:
      - "9000:9000"
    restart: always
    # if the connection to the mysql emartdb fails, need to keep restarting until connect is made.
    container_name: webapi
    depends_on:
      - emartdb

  # nginx api gateway for path based redirection
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    # mounted volume to local workspace default.conf file mapped to /etc/nginx/conf.d on container
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    #depends_on:
    #  - client  

  emongo:
    image: mongo:4
    container_name: emongo
    environment:
      - MONGO_INITDB_DATABASE=epoc
      # the nodejs will connect to the database named "epoc"
    ports:
      - "27017:27017"

  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books
